# Generated by Django 3.0.6 on 2020-05-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200514_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lists',
            new_name='List',
        ),
        migrations.AlterModelTable(
            name='list',
            table='List',
        ),
    ]
