# Generated by Django 3.0.6 on 2020-05-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200515_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='daysleft',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='list',
            name='registered',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
