# Generated by Django 3.0.6 on 2020-05-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200515_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='daysleft',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
