# Generated by Django 3.0.6 on 2020-05-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200515_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='daysLeft',
            field=models.NullBooleanField(default=True),
        ),
    ]
