# Generated by Django 3.0.5 on 2020-05-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Job',
            field=models.CharField(choices=[(1, 'Organiser'), (2, 'Participant')], default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
