# Generated by Django 3.0.6 on 2020-05-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200515_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='noofdays',
            field=models.DecimalField(decimal_places=0, default=-1, max_digits=3),
            preserve_default=False,
        ),
    ]
