# Generated by Django 3.0.5 on 2020-05-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200519_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='daysLeft',
        ),
    ]
