# Generated by Django 3.0.5 on 2020-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_list_daysleft'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='daysLeft',
            field=models.BooleanField(default=True),
        ),
    ]
