# Generated by Django 3.0.5 on 2020-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='registered',
            field=models.DecimalField(decimal_places=0, max_digits=7, null=True),
        ),
    ]
