# Generated by Django 3.0.5 on 2020-05-21 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20200520_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='registered',
        ),
        migrations.AddField(
            model_name='list',
            name='register',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='question',
            field=models.FileField(blank=True, upload_to='questions'),
        ),
    ]
