# Generated by Django 3.0.5 on 2020-05-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200521_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Job',
            new_name='role',
        ),
    ]
