# Generated by Django 3.0.5 on 2020-05-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_mails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mails',
        ),
    ]
